#!/bin/bash

TITLE='Flight Experience'
RUN="./console -noheader $1"
SELECT="select hm(sum(Dur)) from flights f left join aircraft a on a.id = f.aircraft_id left join types t on t.id = a.type_id left join roles r on r.id = f.role_id"

if [ -z $1 ]; then
    echo $TITLE
    echo
    echo From: date
    echo Through: date
    exit 1;
fi;

echo "<HTML><HEAD><TITLE>$TITLE</TITLE></HEAD>"
echo "<H1>$TITLE</H1>"

echo 'PIC: '

echo $SELECT "where r.pic;" | $RUN

echo '<BR>SIC: '

echo $SELECT "where r.sic;" | $RUN

echo '<BR>Multi Engine: '

echo $SELECT "where t.multi;" | $RUN

echo '<BR>Total: '

echo $SELECT "where t.total;" | $RUN

echo
echo '</HTML>' 