#!/bin/bash

TITLE='Flight Time Example'
RUN="./console -noheader $1"
SELECT="select hm(sum(Dur)) from flights f left join aircraft a on a.id = f.aircraft_id left join types t on t.id = a.type_id left join roles r on r.id = f.role_id
        where f.date >= '$2' and (f.date <= '$3' or '$3' == '')"

if [ -z $1 ]; then
    echo $TITLE
    echo
    echo From: date
    echo Through: date
    exit 1;
fi;

FROM=$2
THROUGH=$3

echo "<HTML><HEAD><TITLE>$TITLE</TITLE>"
echo "</HEAD>"
echo "<STYLE>"
cat data/style/summary.css
echo "</STYLE>"
echo "<BODY>"
echo "<DIV id='header'>"
echo "<H1>$TITLE</H1>"
echo "</DIV>"

echo '<BR><BR><H2>'
if [  -n "$FROM" ]; then
    if [ -n "$THROUGH" ]; then
	echo "$FROM through $THROUGH"
    else
	echo "From $FROM";
    fi;
else
    if [ -n "$THROUGH" ]; then
	echo "Through $THROUGH";
    fi;
fi;
echo '</H2>'

echo 'PIC: '

echo $SELECT "and r.pic;" | $RUN

echo '<BR>SIC: '

echo $SELECT "and r.sic;" | $RUN

echo '<BR>Multi Engine: '

echo $SELECT "and t.multi;" | $RUN

echo '<BR>Total: '

echo $SELECT "and t.total;" | $RUN

echo "</BODY>"
echo '</HTML>' 