#!/bin/bash

TITLE='Flight Time Example'
RUN="./console -noheader $1"
SELECT="select hm(sum(Dur)) from flights f left join aircraft a on a.id = f.aircraft_id left join types t on t.id = a.type_id left join roles r on r.id = f.role_id
        where f.date >= '$2' and (f.date <= '$3' or '$3' == '')"

if [ -z $1 ]; then
    echo $TITLE
    echo
    echo From: date
    echo Through: date
    exit 1;
fi;

echo "<HTML><HEAD><TITLE>$TITLE</TITLE>"
echo "</HEAD>"
echo "<H1 style=\"background-color:#F00;\">$TITLE</H1>"

echo '<BR><BR>'
echo "<H2>$2 through $3</H2>"

echo 'PIC: '

echo $SELECT "and r.pic;" | $RUN

echo '<BR>SIC: '

echo $SELECT "and r.sic;" | $RUN

echo '<BR>Multi Engine: '

echo $SELECT "and t.multi;" | $RUN

echo '<BR>Total: '

echo $SELECT "and t.total;" | $RUN

echo
echo '</HTML>' 